### ISSUE TITLE
Jetty dependency: upgrade to major version 10 or 11?

### ISSUE THREAD

**Issue by ztai-add** [logzio/guice-jersey#32]
Hi,

I wonder if there's plan to upgrade the jetty dependency to version 10 or 11? The latest guice-jersey 1.0.16 depends on jetty version [9.4.28.v20200408](https://mvnrepository.com/artifact/org.eclipse.jetty/jetty-server/9.4.28.v20200408) which has some vulnerability issues https://mvnrepository.com/artifact/io.logz/guice-jersey/1.0.16.

Thanks,
Zhenfei

**Comment by kdombeck** [comment]
One problem that I have is that if I try to upgrade to Jersey 10.x in my project I get the following issue when I try to start Jetty.
```
Exception in thread "main" java.lang.NoSuchMethodError: 'void org.eclipse.jetty.webapp.WebAppContext.addEventListener(java.util.EventListener)'
	at io.logz.guice.jersey.JerseyServer.configureServer(JerseyServer.java:83)
	at io.logz.guice.jersey.JerseyServer.<init>(JerseyServer.java:46)
	at io.logz.guice.jersey.JerseyModule.configure(JerseyModule.java:37)
	at com.google.inject.AbstractModule.configure(AbstractModule.java:66)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:409)
	at com.google.inject.spi.Elements.getElements(Elements.java:108)
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:160)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107)
	at com.google.inject.Guice.createInjector(Guice.java:87)
	at com.google.inject.Guice.createInjector(Guice.java:69)
...
```
Seems like the method signature in [ServletContextHandler](https://github.com/eclipse/jetty.project/blob/jetty-10.0.x/jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletContextHandler.java#L207) has changed to return a **boolean** rather than be **void** causing this [issue](https://stackoverflow.com/questions/1134054/changing-return-type-of-method-gives-java-lang-nosuchmethoderror).
